ERROR 2018-08-18 10:06:19,015 exception 80 Invalid HTTP_HOST header: 'api.meiduo.site:8000'. You may need to add 'api.meiduo.site' to ALLOWED_HOSTS.
ERROR 2018-08-18 10:06:19,016 exception 80 Invalid HTTP_HOST header: 'api.meiduo.site:8000'. You may need to add 'api.meiduo.site' to ALLOWED_HOSTS.
ERROR 2018-08-18 10:06:19,016 exception 80 Invalid HTTP_HOST header: 'api.meiduo.site:8000'. You may need to add 'api.meiduo.site' to ALLOWED_HOSTS.
WARNING 2018-08-18 10:06:19,162 basehttp 124 "GET /categories/157/skus/?page=1&page_size=5&ordering=-create_time HTTP/1.1" 400 70445
WARNING 2018-08-18 10:06:19,168 basehttp 124 "OPTIONS /cart/ HTTP/1.1" 400 69695
WARNING 2018-08-18 10:06:19,172 basehttp 124 "GET /categories/157/ HTTP/1.1" 400 69498
INFO 2018-08-18 10:10:20,083 basehttp 124 "GET / HTTP/1.1" 200 1714
ERROR 2018-08-18 10:13:27,541 exception 80 Invalid HTTP_HOST header: 'api.meiduo.site:8000'. You may need to add 'api.meiduo.site' to ALLOWED_HOSTS.
WARNING 2018-08-18 10:13:27,595 basehttp 124 "GET / HTTP/1.1" 400 69973
INFO 2018-08-18 10:15:16,467 basehttp 124 "GET / HTTP/1.1" 200 1714
INFO 2018-08-18 10:18:20,433 basehttp 124 "GET / HTTP/1.1" 200 1714
ERROR 2018-08-18 10:20:47,028 exception 80 Invalid HTTP_HOST header: 'www.meiduo.site:8000'. You may need to add 'www.meiduo.site' to ALLOWED_HOSTS.
WARNING 2018-08-18 10:20:47,104 basehttp 124 "GET / HTTP/1.1" 400 69249
WARNING 2018-08-18 12:04:30,427 base 152 Not Found: /mobiles/13123456789/count/
WARNING 2018-08-18 12:04:30,431 basehttp 124 "GET /mobiles/13123456789/count/ HTTP/1.1" 404 2207
WARNING 2018-08-18 12:04:46,808 base 152 Not Found: /mobiles/13123456789/count/
WARNING 2018-08-18 12:04:46,812 base 152 Not Found: /sms_code/13123456789/
WARNING 2018-08-18 12:04:46,813 basehttp 124 "GET /mobiles/13123456789/count/ HTTP/1.1" 404 2207
WARNING 2018-08-18 12:04:46,814 basehttp 124 "GET /sms_code/13123456789/ HTTP/1.1" 404 2186
WARNING 2018-08-18 12:05:18,701 base 152 Not Found: /mobiles/13123456789/count/
WARNING 2018-08-18 12:05:18,709 basehttp 124 "GET /mobiles/13123456789/count/ HTTP/1.1" 404 2206
INFO 2018-08-18 12:05:18,706 basehttp 124 "GET /sms_code/13123456789/ HTTP/1.1" 200 16
WARNING 2018-08-18 12:05:46,551 base 152 Not Found: /mobiles/13123456782/count/
WARNING 2018-08-18 12:05:46,555 basehttp 124 "GET /mobiles/13123456782/count/ HTTP/1.1" 404 2206
WARNING 2018-08-18 12:05:53,309 base 152 Not Found: /mobiles/13123456781/count/
WARNING 2018-08-18 12:05:53,309 basehttp 124 "GET /mobiles/13123456781/count/ HTTP/1.1" 404 2206
WARNING 2018-08-18 12:05:56,951 base 152 Not Found: /mobiles/13123456781/count/
WARNING 2018-08-18 12:05:56,952 basehttp 124 "GET /mobiles/13123456781/count/ HTTP/1.1" 404 2206
INFO 2018-08-18 12:05:56,965 basehttp 124 "GET /sms_code/13123456781/ HTTP/1.1" 200 16
WARNING 2018-08-18 12:10:50,440 base 152 Not Found: /mobiles/13123456789/count/
WARNING 2018-08-18 12:10:50,441 basehttp 124 "GET /mobiles/13123456789/count/ HTTP/1.1" 404 2206
INFO 2018-08-18 12:10:52,726 basehttp 124 "GET /sms_code/13123456789/ HTTP/1.1" 200 16
WARNING 2018-08-18 12:10:52,736 base 152 Not Found: /mobiles/13123456789/count/
WARNING 2018-08-18 12:10:52,736 basehttp 124 "GET /mobiles/13123456789/count/ HTTP/1.1" 404 2206
ERROR 2018-08-18 19:16:01,030 exception 135 Internal Server Error: /mobiles/13112345678/count/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/utils/deprecation.py", line 138, in __call__
    response = self.process_request(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/contrib/auth/middleware.py", line 23, in process_request
    ) % ("_CLASSES" if settings.MIDDLEWARE is None else "")
AssertionError: The Django authentication middleware requires session middleware to be installed. Edit your MIDDLEWARE setting to insert 'django.contrib.sessions.middleware.SessionMiddleware' before 'django.contrib.auth.middleware.AuthenticationMiddleware'.
ERROR 2018-08-18 19:16:01,085 exception 135 Internal Server Error: /sms_code/13112345678/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/utils/deprecation.py", line 138, in __call__
    response = self.process_request(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/contrib/auth/middleware.py", line 23, in process_request
    ) % ("_CLASSES" if settings.MIDDLEWARE is None else "")
AssertionError: The Django authentication middleware requires session middleware to be installed. Edit your MIDDLEWARE setting to insert 'django.contrib.sessions.middleware.SessionMiddleware' before 'django.contrib.auth.middleware.AuthenticationMiddleware'.
ERROR 2018-08-18 19:16:01,402 basehttp 124 "GET /sms_code/13112345678/ HTTP/1.1" 500 66012
ERROR 2018-08-18 19:16:01,445 basehttp 124 "GET /mobiles/13112345678/count/ HTTP/1.1" 500 66080
ERROR 2018-08-18 19:16:01,453 exception 135 Internal Server Error: /mobiles/13112345678/count/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/utils/deprecation.py", line 138, in __call__
    response = self.process_request(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/contrib/auth/middleware.py", line 23, in process_request
    ) % ("_CLASSES" if settings.MIDDLEWARE is None else "")
AssertionError: The Django authentication middleware requires session middleware to be installed. Edit your MIDDLEWARE setting to insert 'django.contrib.sessions.middleware.SessionMiddleware' before 'django.contrib.auth.middleware.AuthenticationMiddleware'.
ERROR 2018-08-18 19:16:01,794 basehttp 124 "GET /mobiles/13112345678/count/ HTTP/1.1" 500 66080
ERROR 2018-08-18 19:16:04,995 exception 135 Internal Server Error: /mobiles/13112345678/count/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/utils/deprecation.py", line 138, in __call__
    response = self.process_request(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/contrib/auth/middleware.py", line 23, in process_request
    ) % ("_CLASSES" if settings.MIDDLEWARE is None else "")
AssertionError: The Django authentication middleware requires session middleware to be installed. Edit your MIDDLEWARE setting to insert 'django.contrib.sessions.middleware.SessionMiddleware' before 'django.contrib.auth.middleware.AuthenticationMiddleware'.
ERROR 2018-08-18 19:16:05,009 exception 135 Internal Server Error: /sms_code/13112345678/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/utils/deprecation.py", line 138, in __call__
    response = self.process_request(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/contrib/auth/middleware.py", line 23, in process_request
    ) % ("_CLASSES" if settings.MIDDLEWARE is None else "")
AssertionError: The Django authentication middleware requires session middleware to be installed. Edit your MIDDLEWARE setting to insert 'django.contrib.sessions.middleware.SessionMiddleware' before 'django.contrib.auth.middleware.AuthenticationMiddleware'.
ERROR 2018-08-18 19:16:05,121 basehttp 124 "GET /mobiles/13112345678/count/ HTTP/1.1" 500 66080
ERROR 2018-08-18 19:16:05,124 basehttp 124 "GET /sms_code/13112345678/ HTTP/1.1" 500 66012
ERROR 2018-08-18 19:16:06,136 exception 135 Internal Server Error: /mobiles/13112345678/count/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/utils/deprecation.py", line 138, in __call__
    response = self.process_request(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/contrib/auth/middleware.py", line 23, in process_request
    ) % ("_CLASSES" if settings.MIDDLEWARE is None else "")
AssertionError: The Django authentication middleware requires session middleware to be installed. Edit your MIDDLEWARE setting to insert 'django.contrib.sessions.middleware.SessionMiddleware' before 'django.contrib.auth.middleware.AuthenticationMiddleware'.
ERROR 2018-08-18 19:16:06,139 exception 135 Internal Server Error: /sms_code/13112345678/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/utils/deprecation.py", line 138, in __call__
    response = self.process_request(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/contrib/auth/middleware.py", line 23, in process_request
    ) % ("_CLASSES" if settings.MIDDLEWARE is None else "")
AssertionError: The Django authentication middleware requires session middleware to be installed. Edit your MIDDLEWARE setting to insert 'django.contrib.sessions.middleware.SessionMiddleware' before 'django.contrib.auth.middleware.AuthenticationMiddleware'.
ERROR 2018-08-18 19:16:06,267 basehttp 124 "GET /sms_code/13112345678/ HTTP/1.1" 500 66012
ERROR 2018-08-18 19:16:06,270 basehttp 124 "GET /mobiles/13112345678/count/ HTTP/1.1" 500 66080
ERROR 2018-08-18 19:16:06,452 exception 135 Internal Server Error: /mobiles/13112345678/count/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/utils/deprecation.py", line 138, in __call__
    response = self.process_request(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/contrib/auth/middleware.py", line 23, in process_request
    ) % ("_CLASSES" if settings.MIDDLEWARE is None else "")
AssertionError: The Django authentication middleware requires session middleware to be installed. Edit your MIDDLEWARE setting to insert 'django.contrib.sessions.middleware.SessionMiddleware' before 'django.contrib.auth.middleware.AuthenticationMiddleware'.
ERROR 2018-08-18 19:16:06,462 exception 135 Internal Server Error: /sms_code/13112345678/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/utils/deprecation.py", line 138, in __call__
    response = self.process_request(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/contrib/auth/middleware.py", line 23, in process_request
    ) % ("_CLASSES" if settings.MIDDLEWARE is None else "")
AssertionError: The Django authentication middleware requires session middleware to be installed. Edit your MIDDLEWARE setting to insert 'django.contrib.sessions.middleware.SessionMiddleware' before 'django.contrib.auth.middleware.AuthenticationMiddleware'.
ERROR 2018-08-18 19:16:06,613 basehttp 124 "GET /mobiles/13112345678/count/ HTTP/1.1" 500 66080
ERROR 2018-08-18 19:16:06,617 basehttp 124 "GET /sms_code/13112345678/ HTTP/1.1" 500 66012
ERROR 2018-08-18 19:16:06,624 exception 135 Internal Server Error: /mobiles/13112345678/count/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/utils/deprecation.py", line 138, in __call__
    response = self.process_request(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/contrib/auth/middleware.py", line 23, in process_request
    ) % ("_CLASSES" if settings.MIDDLEWARE is None else "")
AssertionError: The Django authentication middleware requires session middleware to be installed. Edit your MIDDLEWARE setting to insert 'django.contrib.sessions.middleware.SessionMiddleware' before 'django.contrib.auth.middleware.AuthenticationMiddleware'.
ERROR 2018-08-18 19:16:06,648 exception 135 Internal Server Error: /sms_code/13112345678/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/utils/deprecation.py", line 138, in __call__
    response = self.process_request(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/contrib/auth/middleware.py", line 23, in process_request
    ) % ("_CLASSES" if settings.MIDDLEWARE is None else "")
AssertionError: The Django authentication middleware requires session middleware to be installed. Edit your MIDDLEWARE setting to insert 'django.contrib.sessions.middleware.SessionMiddleware' before 'django.contrib.auth.middleware.AuthenticationMiddleware'.
ERROR 2018-08-18 19:16:06,884 basehttp 124 "GET /mobiles/13112345678/count/ HTTP/1.1" 500 66080
ERROR 2018-08-18 19:16:06,909 basehttp 124 "GET /sms_code/13112345678/ HTTP/1.1" 500 66012
ERROR 2018-08-18 19:16:06,947 exception 135 Internal Server Error: /mobiles/13112345678/count/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/utils/deprecation.py", line 138, in __call__
    response = self.process_request(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/contrib/auth/middleware.py", line 23, in process_request
    ) % ("_CLASSES" if settings.MIDDLEWARE is None else "")
AssertionError: The Django authentication middleware requires session middleware to be installed. Edit your MIDDLEWARE setting to insert 'django.contrib.sessions.middleware.SessionMiddleware' before 'django.contrib.auth.middleware.AuthenticationMiddleware'.
ERROR 2018-08-18 19:16:06,956 exception 135 Internal Server Error: /sms_code/13112345678/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/utils/deprecation.py", line 138, in __call__
    response = self.process_request(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/contrib/auth/middleware.py", line 23, in process_request
    ) % ("_CLASSES" if settings.MIDDLEWARE is None else "")
AssertionError: The Django authentication middleware requires session middleware to be installed. Edit your MIDDLEWARE setting to insert 'django.contrib.sessions.middleware.SessionMiddleware' before 'django.contrib.auth.middleware.AuthenticationMiddleware'.
ERROR 2018-08-18 19:16:07,125 basehttp 124 "GET /mobiles/13112345678/count/ HTTP/1.1" 500 66080
ERROR 2018-08-18 19:16:07,135 basehttp 124 "GET /sms_code/13112345678/ HTTP/1.1" 500 66012
ERROR 2018-08-18 19:16:07,276 exception 135 Internal Server Error: /mobiles/13112345678/count/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/utils/deprecation.py", line 138, in __call__
    response = self.process_request(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/contrib/auth/middleware.py", line 23, in process_request
    ) % ("_CLASSES" if settings.MIDDLEWARE is None else "")
AssertionError: The Django authentication middleware requires session middleware to be installed. Edit your MIDDLEWARE setting to insert 'django.contrib.sessions.middleware.SessionMiddleware' before 'django.contrib.auth.middleware.AuthenticationMiddleware'.
ERROR 2018-08-18 19:16:07,287 exception 135 Internal Server Error: /sms_code/13112345678/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/utils/deprecation.py", line 138, in __call__
    response = self.process_request(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/contrib/auth/middleware.py", line 23, in process_request
    ) % ("_CLASSES" if settings.MIDDLEWARE is None else "")
AssertionError: The Django authentication middleware requires session middleware to be installed. Edit your MIDDLEWARE setting to insert 'django.contrib.sessions.middleware.SessionMiddleware' before 'django.contrib.auth.middleware.AuthenticationMiddleware'.
ERROR 2018-08-18 19:16:07,466 basehttp 124 "GET /sms_code/13112345678/ HTTP/1.1" 500 66012
ERROR 2018-08-18 19:16:07,492 basehttp 124 "GET /mobiles/13112345678/count/ HTTP/1.1" 500 66080
ERROR 2018-08-18 19:16:07,638 exception 135 Internal Server Error: /mobiles/13112345678/count/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/utils/deprecation.py", line 138, in __call__
    response = self.process_request(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/contrib/auth/middleware.py", line 23, in process_request
    ) % ("_CLASSES" if settings.MIDDLEWARE is None else "")
AssertionError: The Django authentication middleware requires session middleware to be installed. Edit your MIDDLEWARE setting to insert 'django.contrib.sessions.middleware.SessionMiddleware' before 'django.contrib.auth.middleware.AuthenticationMiddleware'.
ERROR 2018-08-18 19:16:07,642 exception 135 Internal Server Error: /sms_code/13112345678/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/utils/deprecation.py", line 138, in __call__
    response = self.process_request(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/contrib/auth/middleware.py", line 23, in process_request
    ) % ("_CLASSES" if settings.MIDDLEWARE is None else "")
AssertionError: The Django authentication middleware requires session middleware to be installed. Edit your MIDDLEWARE setting to insert 'django.contrib.sessions.middleware.SessionMiddleware' before 'django.contrib.auth.middleware.AuthenticationMiddleware'.
ERROR 2018-08-18 19:16:07,856 basehttp 124 "GET /mobiles/13112345678/count/ HTTP/1.1" 500 66080
ERROR 2018-08-18 19:16:07,868 basehttp 124 "GET /sms_code/13112345678/ HTTP/1.1" 500 66012
ERROR 2018-08-18 19:16:08,041 exception 135 Internal Server Error: /mobiles/13112345678/count/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/utils/deprecation.py", line 138, in __call__
    response = self.process_request(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/contrib/auth/middleware.py", line 23, in process_request
    ) % ("_CLASSES" if settings.MIDDLEWARE is None else "")
AssertionError: The Django authentication middleware requires session middleware to be installed. Edit your MIDDLEWARE setting to insert 'django.contrib.sessions.middleware.SessionMiddleware' before 'django.contrib.auth.middleware.AuthenticationMiddleware'.
ERROR 2018-08-18 19:16:08,076 exception 135 Internal Server Error: /sms_code/13112345678/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/utils/deprecation.py", line 138, in __call__
    response = self.process_request(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/contrib/auth/middleware.py", line 23, in process_request
    ) % ("_CLASSES" if settings.MIDDLEWARE is None else "")
AssertionError: The Django authentication middleware requires session middleware to be installed. Edit your MIDDLEWARE setting to insert 'django.contrib.sessions.middleware.SessionMiddleware' before 'django.contrib.auth.middleware.AuthenticationMiddleware'.
ERROR 2018-08-18 19:16:08,453 basehttp 124 "GET /mobiles/13112345678/count/ HTTP/1.1" 500 66080
ERROR 2018-08-18 19:16:08,483 basehttp 124 "GET /sms_code/13112345678/ HTTP/1.1" 500 66012
ERROR 2018-08-18 19:16:08,543 exception 135 Internal Server Error: /mobiles/13112345678/count/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/utils/deprecation.py", line 138, in __call__
    response = self.process_request(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/contrib/auth/middleware.py", line 23, in process_request
    ) % ("_CLASSES" if settings.MIDDLEWARE is None else "")
AssertionError: The Django authentication middleware requires session middleware to be installed. Edit your MIDDLEWARE setting to insert 'django.contrib.sessions.middleware.SessionMiddleware' before 'django.contrib.auth.middleware.AuthenticationMiddleware'.
ERROR 2018-08-18 19:16:08,553 exception 135 Internal Server Error: /sms_code/13112345678/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/utils/deprecation.py", line 138, in __call__
    response = self.process_request(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/contrib/auth/middleware.py", line 23, in process_request
    ) % ("_CLASSES" if settings.MIDDLEWARE is None else "")
AssertionError: The Django authentication middleware requires session middleware to be installed. Edit your MIDDLEWARE setting to insert 'django.contrib.sessions.middleware.SessionMiddleware' before 'django.contrib.auth.middleware.AuthenticationMiddleware'.
ERROR 2018-08-18 19:16:08,910 basehttp 124 "GET /sms_code/13112345678/ HTTP/1.1" 500 66012
ERROR 2018-08-18 19:16:08,921 basehttp 124 "GET /mobiles/13112345678/count/ HTTP/1.1" 500 66080
ERROR 2018-08-18 19:16:09,149 exception 135 Internal Server Error: /mobiles/13112345678/count/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/utils/deprecation.py", line 138, in __call__
    response = self.process_request(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/contrib/auth/middleware.py", line 23, in process_request
    ) % ("_CLASSES" if settings.MIDDLEWARE is None else "")
AssertionError: The Django authentication middleware requires session middleware to be installed. Edit your MIDDLEWARE setting to insert 'django.contrib.sessions.middleware.SessionMiddleware' before 'django.contrib.auth.middleware.AuthenticationMiddleware'.
ERROR 2018-08-18 19:16:09,163 exception 135 Internal Server Error: /sms_code/13112345678/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/utils/deprecation.py", line 138, in __call__
    response = self.process_request(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/contrib/auth/middleware.py", line 23, in process_request
    ) % ("_CLASSES" if settings.MIDDLEWARE is None else "")
AssertionError: The Django authentication middleware requires session middleware to be installed. Edit your MIDDLEWARE setting to insert 'django.contrib.sessions.middleware.SessionMiddleware' before 'django.contrib.auth.middleware.AuthenticationMiddleware'.
ERROR 2018-08-18 19:16:09,577 basehttp 124 "GET /mobiles/13112345678/count/ HTTP/1.1" 500 66080
ERROR 2018-08-18 19:16:09,642 basehttp 124 "GET /sms_code/13112345678/ HTTP/1.1" 500 66012
ERROR 2018-08-18 19:16:09,704 exception 135 Internal Server Error: /mobiles/13112345678/count/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/utils/deprecation.py", line 138, in __call__
    response = self.process_request(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/contrib/auth/middleware.py", line 23, in process_request
    ) % ("_CLASSES" if settings.MIDDLEWARE is None else "")
AssertionError: The Django authentication middleware requires session middleware to be installed. Edit your MIDDLEWARE setting to insert 'django.contrib.sessions.middleware.SessionMiddleware' before 'django.contrib.auth.middleware.AuthenticationMiddleware'.
ERROR 2018-08-18 19:16:09,740 exception 135 Internal Server Error: /sms_code/13112345678/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/utils/deprecation.py", line 138, in __call__
    response = self.process_request(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/contrib/auth/middleware.py", line 23, in process_request
    ) % ("_CLASSES" if settings.MIDDLEWARE is None else "")
AssertionError: The Django authentication middleware requires session middleware to be installed. Edit your MIDDLEWARE setting to insert 'django.contrib.sessions.middleware.SessionMiddleware' before 'django.contrib.auth.middleware.AuthenticationMiddleware'.
ERROR 2018-08-18 19:16:10,213 basehttp 124 "GET /mobiles/13112345678/count/ HTTP/1.1" 500 66080
ERROR 2018-08-18 19:16:10,261 basehttp 124 "GET /sms_code/13112345678/ HTTP/1.1" 500 66012
ERROR 2018-08-18 19:16:10,299 exception 135 Internal Server Error: /mobiles/13112345678/count/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/utils/deprecation.py", line 138, in __call__
    response = self.process_request(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/contrib/auth/middleware.py", line 23, in process_request
    ) % ("_CLASSES" if settings.MIDDLEWARE is None else "")
AssertionError: The Django authentication middleware requires session middleware to be installed. Edit your MIDDLEWARE setting to insert 'django.contrib.sessions.middleware.SessionMiddleware' before 'django.contrib.auth.middleware.AuthenticationMiddleware'.
ERROR 2018-08-18 19:16:10,311 exception 135 Internal Server Error: /sms_code/13112345678/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/utils/deprecation.py", line 138, in __call__
    response = self.process_request(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/contrib/auth/middleware.py", line 23, in process_request
    ) % ("_CLASSES" if settings.MIDDLEWARE is None else "")
AssertionError: The Django authentication middleware requires session middleware to be installed. Edit your MIDDLEWARE setting to insert 'django.contrib.sessions.middleware.SessionMiddleware' before 'django.contrib.auth.middleware.AuthenticationMiddleware'.
ERROR 2018-08-18 19:16:10,653 basehttp 124 "GET /mobiles/13112345678/count/ HTTP/1.1" 500 66080
ERROR 2018-08-18 19:16:10,661 basehttp 124 "GET /sms_code/13112345678/ HTTP/1.1" 500 66012
ERROR 2018-08-18 19:16:10,803 exception 135 Internal Server Error: /mobiles/13112345678/count/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/utils/deprecation.py", line 138, in __call__
    response = self.process_request(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/contrib/auth/middleware.py", line 23, in process_request
    ) % ("_CLASSES" if settings.MIDDLEWARE is None else "")
AssertionError: The Django authentication middleware requires session middleware to be installed. Edit your MIDDLEWARE setting to insert 'django.contrib.sessions.middleware.SessionMiddleware' before 'django.contrib.auth.middleware.AuthenticationMiddleware'.
ERROR 2018-08-18 19:16:10,817 exception 135 Internal Server Error: /sms_code/13112345678/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/utils/deprecation.py", line 138, in __call__
    response = self.process_request(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/contrib/auth/middleware.py", line 23, in process_request
    ) % ("_CLASSES" if settings.MIDDLEWARE is None else "")
AssertionError: The Django authentication middleware requires session middleware to be installed. Edit your MIDDLEWARE setting to insert 'django.contrib.sessions.middleware.SessionMiddleware' before 'django.contrib.auth.middleware.AuthenticationMiddleware'.
ERROR 2018-08-18 19:16:11,147 basehttp 124 "GET /sms_code/13112345678/ HTTP/1.1" 500 66012
ERROR 2018-08-18 19:16:11,150 basehttp 124 "GET /mobiles/13112345678/count/ HTTP/1.1" 500 66080
ERROR 2018-08-18 19:16:11,198 exception 135 Internal Server Error: /mobiles/13112345678/count/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/utils/deprecation.py", line 138, in __call__
    response = self.process_request(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/contrib/auth/middleware.py", line 23, in process_request
    ) % ("_CLASSES" if settings.MIDDLEWARE is None else "")
AssertionError: The Django authentication middleware requires session middleware to be installed. Edit your MIDDLEWARE setting to insert 'django.contrib.sessions.middleware.SessionMiddleware' before 'django.contrib.auth.middleware.AuthenticationMiddleware'.
ERROR 2018-08-18 19:16:11,205 exception 135 Internal Server Error: /sms_code/13112345678/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/utils/deprecation.py", line 138, in __call__
    response = self.process_request(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/contrib/auth/middleware.py", line 23, in process_request
    ) % ("_CLASSES" if settings.MIDDLEWARE is None else "")
AssertionError: The Django authentication middleware requires session middleware to be installed. Edit your MIDDLEWARE setting to insert 'django.contrib.sessions.middleware.SessionMiddleware' before 'django.contrib.auth.middleware.AuthenticationMiddleware'.
ERROR 2018-08-18 19:16:11,568 basehttp 124 "GET /sms_code/13112345678/ HTTP/1.1" 500 66012
ERROR 2018-08-18 19:16:11,616 basehttp 124 "GET /mobiles/13112345678/count/ HTTP/1.1" 500 66080
ERROR 2018-08-18 19:16:11,748 exception 135 Internal Server Error: /mobiles/13112345678/count/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/utils/deprecation.py", line 138, in __call__
    response = self.process_request(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/contrib/auth/middleware.py", line 23, in process_request
    ) % ("_CLASSES" if settings.MIDDLEWARE is None else "")
AssertionError: The Django authentication middleware requires session middleware to be installed. Edit your MIDDLEWARE setting to insert 'django.contrib.sessions.middleware.SessionMiddleware' before 'django.contrib.auth.middleware.AuthenticationMiddleware'.
ERROR 2018-08-18 19:16:11,763 exception 135 Internal Server Error: /sms_code/13112345678/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/utils/deprecation.py", line 138, in __call__
    response = self.process_request(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/contrib/auth/middleware.py", line 23, in process_request
    ) % ("_CLASSES" if settings.MIDDLEWARE is None else "")
AssertionError: The Django authentication middleware requires session middleware to be installed. Edit your MIDDLEWARE setting to insert 'django.contrib.sessions.middleware.SessionMiddleware' before 'django.contrib.auth.middleware.AuthenticationMiddleware'.
ERROR 2018-08-18 19:16:12,107 basehttp 124 "GET /mobiles/13112345678/count/ HTTP/1.1" 500 66080
ERROR 2018-08-18 19:16:12,122 basehttp 124 "GET /sms_code/13112345678/ HTTP/1.1" 500 66012
ERROR 2018-08-18 19:16:48,216 exception 135 Internal Server Error: /sms_code/13112345678/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/utils/deprecation.py", line 138, in __call__
    response = self.process_request(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/contrib/auth/middleware.py", line 23, in process_request
    ) % ("_CLASSES" if settings.MIDDLEWARE is None else "")
AssertionError: The Django authentication middleware requires session middleware to be installed. Edit your MIDDLEWARE setting to insert 'django.contrib.sessions.middleware.SessionMiddleware' before 'django.contrib.auth.middleware.AuthenticationMiddleware'.
ERROR 2018-08-18 19:16:48,219 exception 135 Internal Server Error: /mobiles/13112345678/count/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/utils/deprecation.py", line 138, in __call__
    response = self.process_request(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/contrib/auth/middleware.py", line 23, in process_request
    ) % ("_CLASSES" if settings.MIDDLEWARE is None else "")
AssertionError: The Django authentication middleware requires session middleware to be installed. Edit your MIDDLEWARE setting to insert 'django.contrib.sessions.middleware.SessionMiddleware' before 'django.contrib.auth.middleware.AuthenticationMiddleware'.
ERROR 2018-08-18 19:16:48,400 basehttp 124 "GET /mobiles/13112345678/count/ HTTP/1.1" 500 66341
ERROR 2018-08-18 19:16:48,441 basehttp 124 "GET /sms_code/13112345678/ HTTP/1.1" 500 66273
ERROR 2018-08-18 19:18:13,520 exception 135 Internal Server Error: /sms_code/13112345678/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/python/Desktop/MeiDuoMall/meiduo/apps/verifications/views.py", line 17, in get
    redis_cli = get_redis_connection('verify_code')
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django_redis/__init__.py", line 14, in get_redis_connection
    cache = caches[alias]
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/core/cache/__init__.py", line 77, in __getitem__
    "Could not find config for '%s' in settings.CACHES" % alias
django.core.cache.backends.base.InvalidCacheBackendError: Could not find config for 'verify_code' in settings.CACHES

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/rest_framework/settings.py", line 183, in import_from_string
    module = import_module(module_path)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 944, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'meiduo.utils'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/rest_framework/views.py", line 437, in handle_exception
    exception_handler = self.get_exception_handler()
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/rest_framework/views.py", line 288, in get_exception_handler
    return self.settings.EXCEPTION_HANDLER
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/rest_framework/settings.py", line 227, in __getattr__
    val = perform_import(val, attr)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/rest_framework/settings.py", line 170, in perform_import
    return import_from_string(val, setting_name)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/rest_framework/settings.py", line 187, in import_from_string
    raise ImportError(msg)
ImportError: Could not import 'meiduo.utils.exceptions.exception_handler' for API setting 'EXCEPTION_HANDLER'. ImportError: No module named 'meiduo.utils'.
WARNING 2018-08-18 19:18:13,523 base 152 Not Found: /mobiles/13112345678/count/
WARNING 2018-08-18 19:18:13,564 basehttp 124 "GET /mobiles/13112345678/count/ HTTP/1.1" 404 2202
ERROR 2018-08-18 19:18:14,366 basehttp 124 "GET /sms_code/13112345678/ HTTP/1.1" 500 128159
WARNING 2018-08-18 19:30:53,616 base 152 Not Found: /mobiles/13155009857/count/
ERROR 2018-08-18 19:30:53,632 exception 135 Internal Server Error: /sms_code/13155009857/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/python/Desktop/MeiDuoMall/meiduo/apps/verifications/views.py", line 17, in get
    redis_cli = get_redis_connection('verify_code')
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django_redis/__init__.py", line 14, in get_redis_connection
    cache = caches[alias]
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/core/cache/__init__.py", line 77, in __getitem__
    "Could not find config for '%s' in settings.CACHES" % alias
django.core.cache.backends.base.InvalidCacheBackendError: Could not find config for 'verify_code' in settings.CACHES
WARNING 2018-08-18 19:30:53,625 base 152 Not Found: /mobiles/13155009857/count/
WARNING 2018-08-18 19:30:53,648 basehttp 124 "GET /mobiles/13155009857/count/ HTTP/1.1" 404 2202
WARNING 2018-08-18 19:30:53,635 basehttp 124 "GET /mobiles/13155009857/count/ HTTP/1.1" 404 2202
ERROR 2018-08-18 19:30:53,739 basehttp 124 "GET /sms_code/13155009857/ HTTP/1.1" 500 17656
WARNING 2018-08-18 19:32:11,561 base 152 Not Found: /mobiles/13155009857/count/
WARNING 2018-08-18 19:32:11,582 basehttp 124 "GET /mobiles/13155009857/count/ HTTP/1.1" 404 2202
WARNING 2018-08-18 19:32:11,616 base 152 Not Found: /mobiles/13155009857/count/
WARNING 2018-08-18 19:32:11,616 basehttp 124 "GET /mobiles/13155009857/count/ HTTP/1.1" 404 2202
INFO 2018-08-18 19:32:11,647 basehttp 124 "GET /sms_code/13155009857/ HTTP/1.1" 200 16
WARNING 2018-08-19 15:34:10,393 base 152 Not Found: /mobiles/13112345678/count/
WARNING 2018-08-19 15:34:10,387 base 152 Not Found: /mobiles/13112345678/count/
WARNING 2018-08-19 15:34:10,432 basehttp 124 "GET /mobiles/13112345678/count/ HTTP/1.1" 404 2202
WARNING 2018-08-19 15:34:10,437 basehttp 124 "GET /mobiles/13112345678/count/ HTTP/1.1" 404 2202
INFO 2018-08-19 15:34:10,604 basehttp 124 "GET /sms_code/13112345678/ HTTP/1.1" 200 16
WARNING 2018-08-19 15:44:27,143 base 152 Not Found: /usernames/bobers/count/
WARNING 2018-08-19 15:44:27,146 basehttp 124 "GET /usernames/bobers/count/ HTTP/1.1" 404 2193
WARNING 2018-08-19 15:46:09,294 base 152 Not Found: /usernames/bobers/count/
WARNING 2018-08-19 15:46:09,302 basehttp 124 "GET /usernames/bobers/count/ HTTP/1.1" 404 2193
WARNING 2018-08-19 15:47:36,081 base 152 Not Found: /usernames/bobers/count/
WARNING 2018-08-19 15:47:36,082 basehttp 124 "GET /usernames/bobers/count/ HTTP/1.1" 404 2193
WARNING 2018-08-19 15:48:18,196 base 152 Not Found: /usernames/bobers/count/
WARNING 2018-08-19 15:48:18,196 basehttp 124 "GET /usernames/bobers/count/ HTTP/1.1" 404 2193
INFO 2018-08-19 21:10:38,693 basehttp 124 "GET /usernames/smith/count/ HTTP/1.1" 200 30
INFO 2018-08-19 21:11:01,253 basehttp 124 "GET /mobiles/13012345678/count/ HTTP/1.1" 200 34
INFO 2018-08-19 21:11:01,323 basehttp 124 "GET /mobiles/13012345678/count/ HTTP/1.1" 200 34
INFO 2018-08-19 21:11:01,379 basehttp 124 "GET /sms_code/13012345678/ HTTP/1.1" 200 16
INFO 2018-08-19 21:11:11,397 basehttp 124 "OPTIONS /users/ HTTP/1.1" 200 0
INFO 2018-08-19 21:11:11,405 basehttp 124 "GET /usernames/smith/count/ HTTP/1.1" 200 30
INFO 2018-08-19 21:11:11,423 basehttp 124 "GET /mobiles/13012345678/count/ HTTP/1.1" 200 34
INFO 2018-08-19 21:11:11,510 basehttp 124 "POST /users/ HTTP/1.1" 201 50
WARNING 2018-08-21 14:58:53,485 base 152 Not Found: /
WARNING 2018-08-21 14:58:53,494 basehttp 124 "GET / HTTP/1.1" 404 2651
WARNING 2018-08-21 14:58:53,623 base 152 Not Found: /favicon.ico
WARNING 2018-08-21 14:58:53,629 basehttp 124 "GET /favicon.ico HTTP/1.1" 404 2702
WARNING 2018-08-21 15:15:32,277 base 152 Not Found: /
WARNING 2018-08-21 15:15:32,279 basehttp 124 "GET / HTTP/1.1" 404 2816
WARNING 2018-08-21 15:15:43,183 base 152 Not Found: /authonrizations
WARNING 2018-08-21 15:15:43,196 basehttp 124 "GET /authonrizations HTTP/1.1" 404 2879
WARNING 2018-08-21 15:15:50,073 base 152 Not Found: /authonrizations/
WARNING 2018-08-21 15:15:50,089 basehttp 124 "GET /authonrizations/ HTTP/1.1" 404 2882
WARNING 2018-08-21 15:16:07,092 basehttp 124 "GET /authorizations/ HTTP/1.1" 405 7589
INFO 2018-08-21 15:16:07,177 basehttp 124 "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 200 3385
INFO 2018-08-21 15:16:07,191 basehttp 124 "GET /static/rest_framework/css/prettify.css HTTP/1.1" 200 817
INFO 2018-08-21 15:16:07,207 basehttp 124 "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121200
INFO 2018-08-21 15:16:07,217 basehttp 124 "GET /static/rest_framework/css/default.css HTTP/1.1" 200 1131
INFO 2018-08-21 15:16:07,234 basehttp 124 "GET /static/rest_framework/js/jquery-3.3.1.min.js HTTP/1.1" 200 86927
INFO 2018-08-21 15:16:07,237 basehttp 124 "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 200 3597
INFO 2018-08-21 15:16:07,246 basehttp 124 "GET /static/rest_framework/js/csrf.js HTTP/1.1" 200 1735
INFO 2018-08-21 15:16:07,263 basehttp 124 "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 200 37045
INFO 2018-08-21 15:16:07,267 basehttp 124 "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 200 13632
INFO 2018-08-21 15:16:07,268 basehttp 124 "GET /static/rest_framework/js/default.js HTTP/1.1" 200 1262
INFO 2018-08-21 15:16:07,343 basehttp 124 "GET /static/rest_framework/img/grid.png HTTP/1.1" 200 1458
WARNING 2018-08-21 15:16:36,684 basehttp 124 "POST /authorizations/ HTTP/1.1" 400 7640
WARNING 2018-08-21 15:17:24,519 basehttp 124 "POST /authorizations/ HTTP/1.1" 400 7640
WARNING 2018-08-21 15:17:35,671 basehttp 124 "POST /authorizations/ HTTP/1.1" 400 7639
WARNING 2018-08-21 15:17:41,862 basehttp 124 "POST /authorizations/ HTTP/1.1" 400 7638
ERROR 2018-08-21 15:18:12,066 exception 135 Internal Server Error: /authorizations/
Traceback (most recent call last):
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/rest_framework/views.py", line 483, in dispatch
    response = self.handle_exception(exc)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/rest_framework/views.py", line 443, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/rest_framework/views.py", line 480, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/python/.virtualenvs/django_py3/lib/python3.5/site-packages/rest_framework_jwt/views.py", line 60, in post
    response_data = jwt_response_payload_handler(token, user, request)
  File "/home/python/Desktop/MeiDuoMall/meiduo/apps/users/utils.py", line 14, in jwt_response_payload_handler
    'username':user.name
AttributeError: 'User' object has no attribute 'name'
ERROR 2018-08-21 15:18:12,215 basehttp 124 "POST /authorizations/ HTTP/1.1" 500 101027
WARNING 2018-08-21 15:18:59,638 basehttp 124 "GET /authorizations/ HTTP/1.1" 405 7589
INFO 2018-08-21 15:19:08,936 basehttp 124 "POST /authorizations/ HTTP/1.1" 200 7775
INFO 2018-08-21 15:38:55,646 basehttp 124 "POST /authorizations/ HTTP/1.1" 200 7775
INFO 2018-08-21 15:39:09,796 basehttp 124 "POST /authorizations/ HTTP/1.1" 200 7775
INFO 2018-08-21 17:46:07,966 basehttp 124 "GET /users HTTP/1.1" 301 0
WARNING 2018-08-21 17:46:08,086 basehttp 124 "GET /users/ HTTP/1.1" 405 8415
WARNING 2018-08-21 17:47:12,069 base 152 Not Found: /sms_code
WARNING 2018-08-21 17:47:12,073 basehttp 124 "GET /sms_code HTTP/1.1" 404 2858
INFO 2018-08-21 17:47:47,302 basehttp 124 "GET /sms_code/13198765432 HTTP/1.1" 301 0
INFO 2018-08-21 17:47:47,544 basehttp 124 "GET /sms_code/13198765432/ HTTP/1.1" 200 5170
WARNING 2018-08-21 17:48:03,735 basehttp 124 "POST /users/ HTTP/1.1" 400 8579
INFO 2018-08-22 16:59:26,320 basehttp 124 "GET /sms_code/13198765432 HTTP/1.1" 301 0
INFO 2018-08-22 16:59:26,772 basehttp 124 "GET /sms_code/13198765432/ HTTP/1.1" 200 5170
INFO 2018-08-22 16:59:26,796 basehttp 124 "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 304 0
INFO 2018-08-22 16:59:26,797 basehttp 124 "GET /static/rest_framework/css/prettify.css HTTP/1.1" 304 0
INFO 2018-08-22 16:59:26,798 basehttp 124 "GET /static/rest_framework/css/default.css HTTP/1.1" 304 0
INFO 2018-08-22 16:59:26,799 basehttp 124 "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 304 0
INFO 2018-08-22 16:59:26,824 basehttp 124 "GET /static/rest_framework/js/jquery-3.3.1.min.js HTTP/1.1" 304 0
INFO 2018-08-22 16:59:26,846 basehttp 124 "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
INFO 2018-08-22 16:59:26,849 basehttp 124 "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
INFO 2018-08-22 16:59:26,860 basehttp 124 "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
INFO 2018-08-22 16:59:26,871 basehttp 124 "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
INFO 2018-08-22 16:59:26,880 basehttp 124 "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
INFO 2018-08-22 16:59:27,220 basehttp 124 "GET /static/rest_framework/img/grid.png HTTP/1.1" 304 0
WARNING 2018-08-22 16:59:27,600 base 152 Not Found: /favicon.ico
WARNING 2018-08-22 16:59:27,607 basehttp 124 "GET /favicon.ico HTTP/1.1" 404 2974
WARNING 2018-08-22 16:59:30,655 base 152 Not Found: /
WARNING 2018-08-22 16:59:30,664 basehttp 124 "GET / HTTP/1.1" 404 2923
